language: python
python:
    - "2.7"
    - "3.3"
install:
    - pip install -r requirements.txt
script:
    - check-manifest --ignore test*
    - python setup.py check -m -r -s
    - flake8 .
    - py.test test
