language: python
dist: xenial
os: linux

env:
  global:
    - TWINE_USERNAME=1313e
    - secure: "dfjMgQpMYsTzDkbeY2/aCvyGWBOncsA0VOvGlucZ9iS7x6cn+/btICYO7GaFDqgFeWkBveT9KoydOD6oZe390SOQZi0ytNY9N88hZ3wBWB2RDyHx87ykebwoS04cSMAKMhcc1cgY0gI60JVRnydPlD1tKyj6ljif0Sfw36eN2ILniJO5Jrg5E0od8yysWAVXhrGo87FnonLVLI2wFAE/pgfqjjgnPxkpT1IId3FoMioW7/RyVJ3oixTAw4mKDbPjwFCLmD7sSIxca1XDlnvlGQVuz+4Sunb87miXaxGhtWGD/yqvQ2P9rMIAeTWXYa2wDu4MUfBscBDQ7KbdE/PWIZD/3xwEhCx5IPJUxdKpIvep2zTyCRXThP0+8va/h578yI55QWU2FTXWoj2ISlDt32kOsylB3SfrqZJ+2rsCFthQFGRv/Hb0y2r4tn6GXaIt7w3XadWXqtXiAUNsDv4yIecd1rfmVnauXrCAA6Q+S1SNNPUDfzTgrdcWOIIhItmi8Wm5j48qRArLg38ED3a3nxAwQZKEjLOpwXoL2M908v/IR17jnWx0ecDSydc7wP/2aIbLMAUNBhotZ/ui9TvjWnfneyg2thzeMmTCuTjd9WgTRibaYO7DjNPQwtRvxuzQJ7V+0KUAn1CZfQL+rVt/98M5wFUNsxgTDptJJ/cUcwU="

jobs:
  include:
    - os: osx
      python: 2
      language: generic
    - os: osx
      python: 3
      language: generic
      env: PY=3
    - python: 2.7
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.7-dev
    - python: 3.8
    - python: 3.8-dev
    - python: 3.9-dev
  allow_failures:
    - python: 3.9-dev

before_install:
  - python$PY -m pip install --upgrade pip setuptools wheel
  - pip$PY install -r requirements_dev.txt
install:
  - check-manifest
  - python$PY setup.py sdist bdist_wheel
  - twine check dist/*
script:
  - pytest
after_success:
  - curl -s https://codecov.io/bash | bash
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      twine upload --skip-existing dist/*
    fi

notifications:
  email:
    recipients:
      - ellert_vandervelden@outlook.com
    on_success: change
    on_failure: always
